# -*- coding: utf-8 -*-
"""Step1_Camera Integration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqcXNlh8NGPnFGJZlc4ycnacTuYvJ1xz
"""



# Import necessary libraries
add_library('opencv_processing')  # Processing library for OpenCV

# Setup camera feed and OpenCV
def setup():
    size(800, 600)  # Canvas size
    global video, opencv
    video = OpenCV(this, 800, 600)  # Initialize video capture
    video.start()

    # OpenCV object for image processing
    opencv = OpenCV(this, video.width, video.height)
    opencv.startBackgroundSubtraction(5, 3, 0.5)

def draw():
    # Capture the video frame and process it
    video.read()
    opencv.loadImage(video)

    # Edge detection for room boundary detection (using Canny edge detection)
    opencv.findCannyEdges(30, 150)

    # Display the processed frame on the canvas
    image(video, 0, 0)  # Original video feed
    opencv.drawEdges(0, 0)  # Draw the detected edges