# -*- coding: utf-8 -*-
"""Step2_Camera movement tracking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqcXNlh8NGPnFGJZlc4ycnacTuYvJ1xz
"""



import cv2
import mediapipe as mp

# Initialize MediaPipe pose estimation
mp_pose = mp.solutions.pose
pose = mp_pose.Pose()

# Video and OpenCV settings
def setup():
    size(800, 600)
    global video, opencv
    video = OpenCV(this, 800, 600)
    video.start()

def draw():
    # Capture video frame
    video.read()
    img = video.getImage()

    # Convert frame to RGB format for MediaPipe
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Process the frame with MediaPipe for human pose estimation
    results = pose.process(img_rgb)

    # Draw the pose landmarks if detected
    if results.pose_landmarks:
        draw_pose_landmarks(results.pose_landmarks)

    # Display video feed
    image(video, 0, 0)

def draw_pose_landmarks(landmarks):
    # Draw pose landmarks (skeleton) on the video feed
    for landmark in landmarks.landmark:
        x, y = int(landmark.x * width), int(landmark.y * height)
        ellipse(x, y, 10, 10)  # Draw circles at each landmark