# -*- coding: utf-8 -*-
"""Step3b_data logging and export

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqcXNlh8NGPnFGJZlc4ycnacTuYvJ1xz
"""



import pandas as pd

# Store movement data as DataFrame
def save_movement_data():
    df = pd.DataFrame(movement_path, columns=['x', 'y'])
    df.to_csv("movement_data.csv", index=False)